package org.example.bot;

public enum UserState {
    CREATE_PROFILE_LOGIN,
    CREATE_PROFILE_PASSWORD,
    ENTER_NICKNAME,
    ENTER_AGE,
    ENTER_HEIGHT,
    ENTER_WEIGHT,
    SELECT_COURSE,
    VIEW_EXERCISES,
    LOGIN_LOGIN,
    LOGIN_PASSWORD,
    EDIT_PROFILE_LOGIN,
    EDIT_PROFILE_PASSWORD,
    EDIT_PROFILE_NICKNAME,
    EDIT_PROFILE_AGE,
    EDIT_PROFILE_HEIGHT,
    EDIT_PROFILE_WEIGHT,
    ENTER_INGREDIENTS
}